config/routes.rb
Wineclub::Application.routes.draw do
  devise_for :users
  root to: 'microposts#index'
  resources :microposts
  resources :users
  get '/posts', to: 'microposts#index', as: 'posts'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :content, length: {minimum: 2, maximum: 100}
  validates :user_id, numericality: true

  def self.recent
    where('created_at > ?', 1.weeks.ago).pluck(:content, :user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
    @user = User.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @user = @micropost.user
    if @user == nil
      redirect_to edit_micropost_path, alert: 'No user exists! Please change User ID'
    end
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
    if @micropost.user_id != current_user.id
      redirect_to root_path, alert: 'Cannot edit other peoples posts'
    end
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    @micropost.user_id = current_user.id
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
      #@user = @micropost.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @microposts = Micropost.find_all_by_user_id(@user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    content_for(:title, title)
  end
  def description(description)
    content_for(:description, description)
  end
  def keywords(keywords)
    content_for(:keywords, keywords)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, size: '100x100', alt: user.name, class: "img-circle")
  end
  def mini_gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, size: '16x20', alt: user.name, class: "img-mini-thumbnail")
  end
  def med_gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, size: '75x75', alt: user.name, class: "img-rounded")
  end
  def show_gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, size: '50x50', alt: user.name, class: "img-thumbnail")
  end
end

app/views/layouts/_footer.html.erb
<footer class="container">
  <div class="row">

      <div class="col-xs-6 text-left">
        <div>
        <%= link_to "Microposter", posts_path, id: "logo", class: "lead" %> <sub> created by: Sean M. Snyder</sub>
        </div>
      </div>

      <div class="col-xs-6 text-right">
          <div>
          <span><%= link_to " Codeschool", "http://www.codeschool.com", class: "whiten btn btn-sm btn-warning fa fa-code" %></span>
          <span><%= link_to " Ruby Language", "http://www.ruby-lang.org", class: "whiten btn btn-sm btn-danger fa fa-heart" %></span>
          <span><%= link_to " Ruby Rogues", "http://www.rubyrogues.com", class: "whiten btn btn-sm btn-info fa fa-bullseye" %></span>
          <span><%= link_to " Github", "http://www.github.com", class: "whiten btn btn-sm btn-success fa fa-github" %></span>
          </div>
      </div>
  </div>


</footer>

app/views/layouts/_headers.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">
    <nav class="row-fluid">
      <p></p>

      <div class="col-xs-2">
        <%= link_to "Microposter", posts_path, id: "logo", class: "whiten lead" %>
      </div>
      <div class="btn-group pull-right">
        <% if user_signed_in? %>
            <!-- Split button -->
            <div class="btn-group">

              <%= link_to user_path(current_user.id), class: "btn btn-primary hidden-xs" do %>
                  <%= mini_gravatar_for(current_user) %>
                  <i><%= current_user.name %></i>
              <% end %>
              <button type="button" class="btn btn-primary dropdown-toggle hidden-xs" data-toggle="dropdown">
                <span><span><i class="fa fa-cog fa-spin"></i></span></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li class="container col-xs-10"><%= link_to med_gravatar_for(current_user), "http://www.gravatar.com" %></li>
                <li class="divider"></li>
                <li><%= link_to " My Account", edit_user_registration_path(current_user.id), class: "fa fa-user" %></li>
                <li><%= link_to " Posts", user_path(current_user.id), class: "fa fa-list-ul" %></li>
                <li class="divider"></li>
                <li><%= link_to " New Post", new_micropost_path(current_user.id), class: "fa fa-pencil" %></li>
              </ul>
            </div>

            <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-primary hidden-xs" do %>
                <i class="fa fa-sign-out"> Log Out</i>
            <% end %>
        <% else %>
            <%= link_to new_user_registration_path, class: "btn btn-primary hidden-xs" do %>
                <i class="fa fa-power-off"> Sign Up</i>
            <% end %>
                <%= link_to new_user_session_path, class: "btn btn-primary hidden-xs" do %>
                <i class="fa fa-sign-in"> Log in</i>
            <% end %>

        <% end %>

        <%= link_to users_path, class: "btn btn-primary hidden-sm hidden-xs" do %>
            <i class="fa fa-users"> User List</i>
        <% end %>

        <%= link_to posts_path, class: "btn btn-primary hidden-sm hidden-xs" do %>
            <i class="fa fa-check"> All Posts</i>
        <% end %>

      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micropost <% if user_signed_in? %> | <%= current_user.name %> <% else %> <%= yield(:title) %> <% end %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div>
    <%= render 'layouts/headers' %>
  </div>

  <div class="container jumbotron">
    <%= yield %>
    <% if notice %>
      </br>
      <div class="col-xs-4"></div>
      <div class="col-xs-3 text-center alert alert-success">
      <a class="close" data-dismiss="alert">x</a>
    <%= notice %>
      </div>
    <% elsif alert %>
      </br>
      <div class="col-xs-4"></div>
      <div class="acol-xs-3 text-center alert alert-danger">
      <a class="close" data-dismiss="alert">x</a>
    <%= alert %>
      </div>
    <% end %>
  </div>
  <div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/microposts/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@micropost) do |f| %>
      <% if @micropost.errors.any? %>
        <div id="error_explanation" class="alert alert-danger lead">
          <a class="close" data-dismiss="alert">
            x
          </a>
          <h2>
            <%= pluralize(@micropost.errors.count, "Error") %> in Post
          </h2>
          <ul>
            <% @micropost.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %></li>
          </ul>
        </div>
            <% end %>
      <% end %>
  </div>

  <div class="row">

    <div class="col-xs-1">
    </div>

    <div class="btn btn-primary col-xs-12">
      <%= f.label :Post%><br>
      <%= f.text_area(:content, size: '10x10',class: "col-xs-12 text-black")%>
    </div>

    <div class="col-xs-1">
    </div>

  </div>

<br>

  <div class="row-fluid">

    <div class="col-xs-3">
      <%= f.submit :Post, class: "col-xs-12 btn btn-md btn-primary" %>
      <% end %>
    </div>

    <div class="col-xs-6">
    </div>

    <div class="col-xs-3">
      <%= link_to 'Cancel', microposts_path, class: "btn btn-danger" %>
    </div>

  </div>

</div>

app/views/microposts/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-4"></div>
      <div class="col-xs-6">
        <h1 class="lead">Re-imagine<h1 class="lead">Your Post!</h1></h1>
      </div>
      <div class="col-xs-4"></div>

    <%= render 'form' %>
    </br>
    <div class="row">
      <div class="col-xs-12">
      </div>
    </div>
   </div>
</div>

app/views/microposts/index.html.erb
<% title " - Home" %>
<div class="container-fluid">
    <div class="lead col-xs-12">

      <h1 class="container text-center lead">Cannon Fodder</h1>
      <h4 class="lead">Everyone is talking... Is it about you? Is it something you need to know?
        Let us have it. Fire away! </h4>
      <h2 class="badge center-block"> </h2>
    </div>
  <br>
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Post</th>
      <th>Big Mouth</th>
      <th>Options</th>
    </tr>
    </thead>
    <tbody>
    <% @microposts.each do |micropost| %>
        <tr>
          <td class="content"><%= micropost.content %></td>
          <td><%= @user.find(micropost.user_id).name %></td>
          <td><%= link_to 'Show', micropost, class: "btn btn-xs btn-primary fa fa-comments" %>
            <% if user_signed_in? && micropost.user_id == current_user.id %>
                <%= link_to 'Edit', edit_micropost_path(micropost), class: "btn btn-xs btn-primary fa fa-edit" %>
                <%= link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger fa fa-trash-o" %></td>
            <% end %>
            </tr>
    <% end %>
    </tbody>
  </table>
  <div class="container">
    <% if user_signed_in? %>
        <div class="col-xs-4"><%= link_to "New Micropost", new_micropost_path, class: "btn btn-default" %></div>
        <div class="col-xs-4"></div>
        <div class="col-xs-4"></div>
        </div>
        </div>
    <% else %>
        <div class="col-xs-3"></div>
        <div class="col-xs-6 label-lg label-primary lead"><%= link_to "Sign up", new_user_registration_path, class: 'label label-info whiten' %>
          or <%= link_to "Log in", new_user_session_path, class: "label label-info whiten" %> to begin posting ...
        </div>
        <div class="col-xs-3"></div>
        </div>
        </div>
    <% end %>

app/views/microposts/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-2"><section>Ready</section></div>
      <div class="col-xs-8">
        <h1 class="lead">Though aquired! Prepare to fire!</h1>
      </div>
      <div class="col-xs-2"><h2>Set!</h2></div>
    </div>

    <div class="row">
      <div class="col-xs-2"></div>
      <div class="well col-xs-8">
        <%= render 'form' %>
      </div>
      <div class="col-xs-2"></div>
    </div>

<%= link_to 'Back', microposts_path, class: "btn btn-default" %>
  </div>
</div>

app/views/microposts/show.html.erb
<div class="container jumbotron">
<% title "- #{@user.name}'s Micro" %>

<h2 class="well lead fa fa-quote-left">
  <%= link_to user_path(@user) do %>
  <%= show_gravatar_for(@user) %> <%= @user.name %>
  <% end %>...
  <td><%= @micropost.content %></td>
  <i class="fa fa-quote-right"></i>
</h2>


<div>
  <% if user_signed_in? && @micropost.user_id == current_user.id %>
    <%= link_to 'Edit', edit_micropost_path(@micropost), class: "btn btn-default"  %> <%= link_to 'Back', microposts_path, class: "btn btn-default"  %>
  <% else %>
    <%= link_to 'Back', microposts_path, class: "btn btn-default"  %>
  <% end %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="center hero-unit">
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <h1 class="col-sm-offset-4 lead">Users List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class: "btn btn-xs btn-primary fa fa-comments" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="none" xmlns="http://www.w3.org/1999/html"><p>  <% provide(:title, @user.name) %>  <h1 class="lead well text-center">    <%= gravatar_for @user %>    <%= @user.name.titleize %>  </h1></p><div class="container"><div class="row"><div class="col-xs-2"></div><div class="col-xs-6"></div><div class="col-xs-4 pull-right">  <small class="label-lg label-primary img-circle fa">    <%= "Joined #{time_ago_in_words(@user.created_at)} ago..." %>  </small></div></div>  </br>  <div class="row">    <div class="col-xs-4"></div>    <div class="col-xs-4"></div>    <div class="col-xs-4"><strong class="badge fa fa-envelope lead"> Email: <div class="label-lg btn btn-primary"><%= @user.email %></div></strong></div>  </div></div><p><table class="table table-striped table-hover">  <thead>    <tr>      <th>Posts:</th>      <th>Date</th>    </tr>  </thead>  <tbody>  <% if @user.microposts.all.empty? %>    <tr>      <td>Nothing posted yet!</td>      <td> </td>    </tr>  <% else%>    <% @microposts.each do |f| %>      <tr>        <td><%= f.content %></td>        <td><%= f.created_at.strftime("%B %e, %G") %></td>      </tr>    <% end %>  </tbody>  <%end%></table></p><div>  <%= link_to 'Back', users_path, class: "btn btn-default" %></div></div>